[package]
name = "ibr"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
failure = "=0.1.1"
image = "=0.19.0"
structopt = "=0.2.7"
structopt-derive = "=0.2.7"
vlog = "=0.1.2"

[[bin]]
name = "ibr"
path = "src/main.rs"
